export const successHTML5InfoRes = {
    audioInfo: {
        "audio/aac": false,
        "audio/alac": false,
        "audio/flac": false,
        "audio/mp4": false,
        "audio/mpeg": false,
        "audio/ogg; codecs=opus": false,
        "audio/ogg; codecs=vorbis": false,
        "audio/webm; codecs=opus": false,
        "audio/webm; codecs=vorbis": false,
    },
    availableAPIInfo: {
        IntersectionObserver: false,
        PushManager: false,
        ResizeObserver: false,
        ServiceWorker: false,
        SharedWorker: false,
        TextTrack: false,
        history: true,
        postMessage: true,
        speechSynthesis: false,
        structuredClone: true,
        webkitSpeechRecognition: false,
        worker: false,
    },
    inputInfo: {
        inputAvailableAttributes: {
            accept: true,
            alt: true,
            autocomplete: true,
            autofocus: true,
            checked: true,
            dirname: false,
            disabled: true,
            form: true,
            formaction: false,
            formenctype: false,
            formmethod: false,
            formnovalidate: false,
            formtarget: false,
            height: false,
            list: true,
            max: true,
            maxlength: false,
            min: true,
            minlength: false,
            multiple: true,
            name: true,
            pattern: true,
            placeholder: true,
            readonly: false,
            required: true,
            size: true,
            src: true,
            step: true,
            value: true,
            width: false,
        },
        inputTypes: {
            color: true,
            date: true,
            datetime: false,
            "datetime-local": true,
            email: true,
            file: true,
            month: true,
            number: true,
            password: true,
            range: true,
            search: true,
            tel: true,
            text: true,
            time: true,
            url: true,
            week: true,
        },
    },
};
