export type MotionControlPattern = 'left' | 'right' | 'up' | 'closer' | 'farther';

export * from './applicant_settings';
export * from './authentication_settings';
export * from './base_settings';
export * from './callbacks';
export * from './camera_settings';
export * from './component_modes';
export * from './face_border_settings';
export * from './face_detection';
export * from './face_detector_settings';
export * from './fingerprint_settings';
export * from './geometry';
export * from './localization';
export * from './logging_settings';
export * from './motion_control_settings';
export * from './raw_video_frame';
export * from './recursive_partial';
export * from './resolution';
export * from './server_connection_settings';
export * from './stage_settings';
export * from './take_face_bestshots_settings';
export * from './ui_kit';
export * from './video_recoding_settings';
