const EnglishLocalizatedMessages = {
    PreparingEnvironment: 'Preparing environment',
    MessageCode: 'Message code: ',
    SomeError: 'An error occurred, please try again later',

    Mode: {
        Authorization: 'Authorization',
        Registration: 'Registration',
    },

    ErrorScreen: {
        TryAgainButton: 'Try again',
    },

    Stages: {
        Initialization: {
            IdentifyApplicantStatus: {
                FormFields: {
                    Labels: {
                        FirstName: 'First name',
                        LastName: 'Last name',
                        Phone: 'Phone',
                        Email: 'Email',
                        ReferenceId: 'ReferenceId',
                    },
                    Errors: {
                        InvalidEmail: 'Invalid email format',
                        MaxLengthField: 'Maximum field length is 150 characters',
                        IsRequired: 'This field is required',
                        WrongPhone: 'Wrong phone number',
                    },
                },
                SubmitButton: {
                    Authorization: 'Continue',
                    Registration: 'Continue',
                },
            },

            SelectCamera: {
                TextHints: {
                    CheckingWebcamOperation: 'Check the webcam for proper operation and image quality',
                },
                Preloader: {
                    RequestingAccessToCamera: 'Requesting access to the camera',
                },
                ContinueButton: 'Continue',
                BackButton: 'Back',
            },

            Description: {
                MotionControl: {
                    Heading: 'Checking Motion Control',
                    Text: 'To pass the inspection successfully, you need to perform several actions. First, you need to determine the initial position of the face. To do this, fix the face in a position that is convenient for you and so that the mask is displayed for a few seconds while the counter is filling up under the player. After determining the starting position, you need to perform a number of actions in the order generated by the system. Actions are commands: turn your head to the right/left, raise your head, approach/move away.  The action is considered completed when the frame around the face changes its color.',
                },
                ContinueButton: 'Continue',
                BackButton: 'Back',
            },

            Errors: {
                InvalidTokenError: 'The request was not executed because the token used is invalid',
                ComponentDisabledError: 'The component is disabled',
                ApplicantIdWithApplicantFieldsError:
                    'Configuration error Only one of the two configuration fields must be passed: applicantFields or applicantId',
                NoEnabledApplicantFieldsError:
                    'Configuration error. At least one enabled field in applicantFields is required',
                NoPrimaryApplicantFieldsError: 'Configuration error. One primary field is required in applicantFields',
                NoPrimaryEnabledApplicantFieldsError:
                    'Configuration error. The primary field in applicantFields must be enabled',
                SeveralPrimaryEnabledApplicantFieldsError:
                    'Configuration error. Only one primary field is required in applicantFields',
                InvalidMotionControlAttemptCountError:
                    'Configuration error. The motionControl.attemptsCount field must be greater than zero',
                EnabledMotionControlWithoutFaceModelError:
                    'Configuration error. If faceModelSettings.modelEnabled is false, then motionControl.enabled must also be false',
                TimeToStartRecordLessThenOneSecondError:
                    'Configuration error. The timeToStartRecord value must be at least 1000ms',
                FailedFetchOfConfigurationError: 'Failed to retrieve component settings',
                NoComponentIdError: 'Integration ID not specified in the component configuration',
                NotValidComponentIdError: 'The integration ID must be in the UUID4 format',
                NoBaseUrlError: 'Base URL of server not specified in the component configuration',
                NoExistIntegrationError:
                    'Integration does not exist on the server. Check the integration ID and the server address',
                PrepareEnvironmentForBiometricInspectionTimeoutError:
                    'The waiting time for the initialization of biometric verification services has been exceeded',
                NoRequiredConfigurationFieldsError:
                    'The settings received from the server do not contain the required data',
                InitializationProcessingVideoStremWorkerError: 'Error initializing the video frame processing service',
                InitializationFaceDetectionServiceError: 'Error initializing the face detection service',
                ApplicantNotFoundError: 'Applicant not found',
                ApplicantAlreadyExistError: 'This applicant already exists',
                ApplicantBlockedError: 'The applicant is blocked',
                ApplicantUnconfirmedError: 'The applicant is unconfirmed',
                ApplicantNotRegisterError: 'The application is not registered',
                NotSupportedMediaDevicesError: 'The browser does not support the Media Devices API',
                AbortAccessToCameraError: 'The attempt to access the camera was aborted',
                DocumentIsNotFullyActiveError: 'HTML document is not fully active',
                NotAllowedAccessToCameraError: 'Not allowed access to camera',
                TimeoutAccessToCameraError: 'The waiting time for permission to access the camera has been exceeded',
                NotFoundCameraError: 'No camera was found',
                NotReadableCameraError: 'The camera is unavailable because it is already in use by another process',
                OverconstrainedCameraError: 'No camera satisfying the constraints of the system is found',
                CameraSecurityError: 'The HTML document does not meet the minimum security requirements for camera use',
                NoVideoTrackError: 'There is no data about the video stream from the camera',
                NoCameraCapabilitiesInfoError:
                    'Information about possible camera settings does not contain the required parameters',
                MediaStreamIsUndefinedError: 'There is no video stream data',
                WebComponentError: 'An error occurred, please try again later',
                ConnectionEstablishmentError: 'An error occurred when establishing the connection',
                VersionCompatibilityError: 'Incompatible versions of components and servers',
                InactiveVideoTrackError: 'The video track of the camera is inactive',
                EndedVideoTrackError: 'The video track of the camera is has been ended',
                DisabledVideoTrackError: 'The video track of the camera is disabled',
                NoWebGLSupportError: 'WebGL is unavailable in the current browser configuration',
                FaceDetectorRunningError: 'The device does not meet the requirements necessary to start the detector',
                NoFaceDetectorError: 'No face detector in the system',
                NotSupportedDelegationModeError: 'Unsupported detector delegate mode',
                NoTestFaceDetectorImageError: 'No test image was found to test the operability of the face detector',
                UnsupportFaceDetectorError:
                    'The face detector cannot be started because the device does not support any of the possible operating modes',
                NotSupportedWebglApiError: 'WebGL API is unavailable in the current browser configuration',
                HardwareAccelerationUnavailableError:
                    'Hardware Acceleration is disabled or not supported by the browser',
                WebSocketTimeoutConnectionError: 'The connection to the server was closed due to inactivity',
                WaitResponseWorkerTimeoutError: 'The waiting time for a response from the worker has expired',
                InvalidAuthenticationTokenError: 'Invalid authentication token format',
            },
        },

        BiomertricalChecks: {
            IdentifyFacePosition: {
                TextHints: {
                    MoveFaceOnCenter:
                        'Please position yourself so that your face is in the center of the circle on the screen',
                    IDontSeeYou: 'You are not visible',
                    FaceOutsideFrame:
                        'Please position yourself so that your face is in the center of the on the screen',
                    LookAtCamera: 'Please, turn your face to the camera',
                    LittleFace: 'Move closer to the camera',
                    BigFace: 'Move further away from the camera',
                    DontMove: "Please don't move",
                    CheckPosition: 'Checking position',
                    TimerBeforeRun: 'Before recording starts',
                },
            },

            MotionControl: {
                TextHints: {
                    AttemptFailed: 'Motion Control attempt failed',
                    SendingDataToServer: 'Sending data to the server',
                    Command: {
                        TurnLeft: 'Turn left',
                        TurnRight: 'Turn right',
                        TurnUp: 'Lift your chin up while continuing to look at the screen',
                        LookAtCenter: 'Look into the camera',
                        Closer: 'Move closer to the camera',
                        Farther: 'Move further away from the camera',
                        Normal: 'Return to the original position',
                    },
                },
            },
            Errors: {
                InvalidTokenError: 'The request was not executed because the token used is invalid',
                SlowEnternet: 'Your internet connection is slow. Image quality assessment may take long',
                InCorrectCamera: 'The selected camera is not available or does not meet the minimum requirements',
                NoCamera: 'No cameras available',
                NoPermission:
                    'Permission to access the camera is not obtained. For further work, allow access to the camera in your browser settings',
                MoreFaces: 'Many faces in the frame',
                SafariError: 'Unfortunately, your browser is temporarily not supported at the moment',
                ServerError: 'The server is temporarily unavailable',
                ServerConfigError: 'Error on the server',
                NotSupportedApiError: 'Your browser does not support the required function',
                TransportError: 'An unexpected error occurred while running the check',
                NotSupportedVideoFormatError: "This browser haven't supported needed video mime type",
                VideoStreamResolutionIsUndefinedError: 'The resolution of the video stream is not defined',
                InvalidVideoStreamResolutionValueError:
                    'The resolution of the video stream contains invalid values, the width or height of the video stream cannot be equal to 0',
                InvalidVideoPreviewResolutionValueError:
                    'The resolution of the video preview contains invalid values, the width or height of the video preview cannot be equal to 0',
                InvalidFrameDataForDetectionError: 'Incorrect frame data for face detection',
                CaptureFaceBestshotTimeoutError: 'Frame collection waiting time exceeded',
                InvalidMotionControlPatternError: 'Invalid Motion Control pattern',
                NoSupportedVideoCodecError: 'The video codec supported by the system is not detected',
                WaitResponseWorkerTimeoutError: 'The waiting time for a response from the worker has expired',
                BrowserNotSupportedWorkerApi: "This browser doesn't support Worker API",
                DeepfakeValidationError: 'Deepfake check failed',
                CameraFpsNotDefinedError: 'The frame rate of the video stream is not defined',
                TransmissionTimeoutError: 'The waiting time for a response from the server has been exceeded',
                InvalidFacesAmountOnFrameError: 'No face or too many faces found',
                InvalidMessageFormatError: 'Invalid message format',
                UndefinedLocalizedMessagesError: 'There are no localized messages for the selected language',
                InvalidVideoDataError: 'Invalid video data',
                WebComponentError: 'An error occurred, please try again later',
                NotSupportedVideoEncoderApiError: "The browser doesn't support Video Encoder API",
                LivenessTransportConnectionTimeoutError:
                    'The connection to the server was closed due to an internal error or exceeding the waiting time',
                InactiveVideoTrackError: 'The video track from the camera is inactive',
                120004: 'FPS too low. Please try again',
                120005: 'Error on the server. Please try again',
                120006: 'Error on the server. Please try again',
                120007: 'Error on the server. Please try again',
                120008: 'Error on the server. Please try again',
                120009: 'Please check the quality of your internet connection and try again',
                120044: 'No reference frames found',
                120052: 'Error on the server. Please try again',
                120053: 'Error on the server. Please try again',
                120054: 'Error on the server. Please try again',
                120055: 'Error while sending a message via DataChannel',
                120057: 'Error in obtaining Motion Control pattern',
                120060: 'Error on the server. Please try again',
                120061: 'No face or multiple faces detected while taking reference image. Please try again',
                180001: 'Invalid websocket message format',
                180003: 'Requesting a video recording of an unsupported type',
                180004: 'There was an error on the server while recording video',
                180005: 'Video processing time has exceeded the limit',
                180006: 'Error in operation of WebSocket connection',
                190003: 'The size of data sent to the server exceeds the allowed size',
                NoWebGLSupportError: 'The device does not support WebGL technology',
                FaceDetectorRunningError: 'The device does not meet the requirements necessary to start the detector',
                NoFaceDetectorError: 'No face detector in the system',
                WebSocketTimeoutConnectionError: 'The connection to the server was closed due to inactivity',
            },
        },

        ValidateFlowResult: {
            SendingDataToServer: 'Sending data to the server',
            Success: {
                Register: 'Registration completed successfully',
                Authorize: 'Authorization completed successfully',
            },
            Errors: {
                NoBestshotsError: 'There are no bestshots to process',
                InvalidTokenError: 'The request was not executed because the token used is invalid',
                AntispoofingValidationError: 'Liveness check failed',
                RegistrationMatchingFailedError: 'An applicant with such biometrics already exists',
                AuthorizationMatchingFailedError: 'No applicant with this biometric was found',
                LowImageQualityError: 'Poor image quality',
                NoFacesFound: 'No face found in the image',
                FacesDontBelongApplicant: 'Face matching check failed',
                MoreFaces: 'Many faces in the frame',
                ServerError: 'The server is temporarily unavailable',
                ServerConfigError: 'Error on the server',
                ApplicantInBlackListError: 'The applicant is on the black list',
                ApplicantRiskError: 'During validation, the risk triggered',
                "Face profile wasn't saved": "Face profile wasn't saved",
                'Face profiles not found': 'Face profiles not found',
                'Face authorization was failed': 'Face authorization was failed',
                'Invalid endeavor info': 'Invalid endeavor info',
                'Endeavor external link not equal to applicant': 'Applicant ID consistency error',
                'Endeavor id is null when required': 'Endeavor id is null when required',
                'No faces found on image': 'No faces found on image',
                'Multiple faces found on image': 'Multiple faces found on image',
                'Error on the server': 'Error on the server',
                'Motion control video is not captured': 'Motion control video is not captured',
                'Motion control video reference template is not captured':
                    'Motion control video reference template is not captured',
                NotSupportedApiError: 'Your browser does not support the required function',
                TransportError: 'An unexpected error occurred while running the check',
                NotSupportedVideoFormatError: "This browser haven't supported needed video mime type",
                VideoStreamResolutionIsUndefinedError: 'The resolution of the video stream is not defined',
                InvalidVideoStreamResolutionValueError:
                    'The resolution of the video stream contains invalid values, the width or height of the video stream cannot be equal to 0',
                InvalidVideoPreviewResolutionValueError:
                    'The resolution of the video preview contains invalid values, the width or height of the video preview cannot be equal to 0',
                InvalidFrameDataForDetectionError: 'Incorrect frame data for face detection',
                CaptureFaceBestshotTimeoutError: 'Frame collection waiting time exceeded',
                InvalidMotionControlPatternError: 'Invalid Motion Control pattern',
                NoSupportedVideoCodecError: 'The video codec supported by the system is not detected',
                WaitResponseWorkerTimeoutError: 'The waiting time for a response from the worker has expired',
                BrowserNotSupportedWorkerApi: "This browser doesn't support Worker API",
                DeepfakeValidationError: 'Deepfake check failed',
                CameraFpsNotDefinedError: 'The frame rate of the video stream is not defined',
                TransmissionTimeoutError: 'The waiting time for a response from the server has been exceeded',
                InvalidFacesAmountOnFrameError: 'No face or too many faces found',
                InvalidMessageFormatError: 'Invalid message format',
                UndefinedLocalizedMessagesError: 'There are no localized messages for the selected language',
                ValidationTimeHasExpiredError: 'Validation time has expired',
                ApplicantBlockedError: 'The applicant is blocked',
                WebComponentError: 'An error occurred, please try again later',
                InvalidEndeavorInfoError: 'The attempt contains invalid data',
                LivenessTransportConnectionTimeoutError:
                    'The connection to the server was closed due to an internal error or exceeding the waiting time',
                120004: 'FPS too low. Please try again',
                120005: 'Error on the server. Please try again',
                120006: 'Error on the server. Please try again',
                120007: 'Error on the server. Please try again',
                120008: 'Error on the server. Please try again',
                120009: 'Please check the quality of your internet connection and try again',
                120029: 'Error on the server. Please try again',
                120044: 'No reference frames found',
                120052: 'Error on the server. Please try again',
                120053: 'Error on the server. Please try again',
                120054: 'Error on the server. Please try again',
                120055: 'Error while sending a message via DataChannel',
                120057: 'Error in obtaining Motion Control pattern',
                120060: 'Error on the server. Please try again',
                120061: 'No face or multiple faces detected while taking reference image. Please try again',
                180001: 'Invalid websocket message format',
                180003: 'Requesting a video recording of an unsupported type',
                180004: 'There was an error on the server while recording video',
                180005: 'Video processing time has exceeded the limit',
                180006: 'Error in operation of WebSocket connection',
                190003: 'The size of data sent to the server exceeds the allowed size',
                1300001:
                    'Poor connection quality, the connection to the server does not meet the necessary requirements',
                WebSocketTimeoutConnectionError: 'The connection to the server was closed due to inactivity',
            },
        },
    },
};

export default EnglishLocalizatedMessages;
