user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format json '{ "remote_addr": "$remote_addr", '
                      '"remote_user": "$remote_user", '
                      '"time_local": "$time_local", '
                      '"request_time": $request_time, '
                      '"request_id": "$request_id", '
                      '"request": "$request", '
                      '"status": $status, '
                      '"body_bytes_sent": "$body_bytes_sent", '
                      '"http_referer": "$http_referer", '
                      '"http_user_agent": "$http_user_agent", '
                      '"http_x_forwarded_for": "$http_x_forwarded_for" } ';

    sendfile        on;
    keepalive_timeout  65;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    access_log /var/log/nginx/access.log json;

    limit_conn_zone $server_name zone=addr:10m;

    server {
        listen 80;
        server_name localhost;

        client_max_body_size 0;

        location /face-detector-template-extractor/ {
            proxy_pass http://face-detector-template-extractor:80;
        }

        location /face-detector-face-fitter/ {
            proxy_pass http://face-detector-face-fitter:80;
        }

        location /deepfake-estimator/ {
            proxy_pass http://deepfake-estimator:80;
        }

        location /verify-matcher/ {
            proxy_pass http://verify-matcher:80;
        }

        location /quality-core {
            proxy_pass http://quality-core:80;
        }

        location /liveness-estimator/ {
            proxy_pass http://liveness-estimator:80;
        }

        location /lrs/ {
            proxy_pass http://video-recorder:8090/;
        }

        location /lrs/ws {
            proxy_pass http://video-recorder:8090/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}

