"""add_la_link

Revision ID: 28d1d3a05a67
Revises: b1dec07e5da9
Create Date: 2024-01-24 09:19:39.053524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d1d3a05a67'
down_revision = 'b1dec07e5da9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endeavor', sa.Column('action_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('endeavor', sa.Column('la_s3_link', sa.VARCHAR(length=100), nullable=True))
    op.alter_column('endeavor', 's3_link', nullable=True, new_column_name="lr_s3_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endeavor', 'action_pattern')
    op.drop_column('endeavor', 'la_s3_link')
    op.alter_column('endeavor', 'lr_s3_link', nullable=True, new_column_name="s3_link")
    # ### end Alembic commands ###
