"""add_retention_tables

Revision ID: 5a96617a6504
Revises: 7af73ea68dc7
Create Date: 2025-10-31 13:17:22.812868

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import Sequence
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.ddl import CreateSequence, DropSequence

# revision identifiers, used by Alembic.
revision = '5a96617a6504'
down_revision = '7af73ea68dc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_retention_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planned_retention_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('actual_retention_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    op.execute(CreateSequence(Sequence("ser_set_lock_id_sequence", start=1, increment=1)))

    op.create_table('service_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lock_id', sa.INTEGER(), server_default=sa.text("nextval('ser_set_lock_id_sequence')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lock_id'),
    sa.UniqueConstraint('id')
    )

    op.create_index(op.f('ix_endeavor_content_endeavor_id'), 'endeavor_content', ['endeavor_id'], unique=False)

    op.drop_constraint('endeavor_content_parent_id_fkey', 'endeavor_content', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('endeavor_content_parent_id_fkey', 'endeavor_content', 'endeavor_content', ['parent_id'], ['id'], ondelete='CASCADE')

    op.drop_index(op.f('ix_endeavor_content_endeavor_id'), table_name='endeavor_content')

    op.drop_table('service_settings')
    op.drop_table('last_retention_result')

    op.execute(DropSequence(Sequence("ser_set_lock_id_sequence")))
    # ### end Alembic commands ###
