"""add_action_pattern_table

Revision ID: 668035509e79
Revises: 28d1d3a05a67
Create Date: 2024-01-25 10:15:21.693350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '668035509e79'
down_revision = '28d1d3a05a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'action_pattern',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('external_link', sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            'creation_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'last_modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_pattern')
    # ### end Alembic commands ###
