"""add_endeavor_content

Revision ID: 7af73ea68dc7
Revises: cc7d5f98f15d
Create Date: 2025-07-15 17:13:11.140136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7af73ea68dc7'
down_revision = 'cc7d5f98f15d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endeavor_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endeavor_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.NUMERIC(), nullable=True),
    sa.Column('s3_links', postgresql.ARRAY(sa.VARCHAR(length=255)), nullable=True),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exception_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endeavor_id'], ['endeavor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['endeavor_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endeavor_content')
    # ### end Alembic commands ###
