"""add_links_to_ref

Revision ID: 7f1ff45e943b
Revises: 0ab056de9369
Create Date: 2024-04-02 11:50:34.357781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1ff45e943b'
down_revision = '0ab056de9369'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endeavor', sa.Column('lr_s3_ref_image_link', sa.VARCHAR(length=100), nullable=True))
    op.add_column('endeavor', sa.Column('la_s3_ref_image_link', sa.VARCHAR(length=100), nullable=True))
    op.add_column('endeavor', sa.Column('lr_s3_ref_template_bsm_link', sa.VARCHAR(length=100), nullable=True))
    op.add_column('endeavor', sa.Column('la_s3_ref_template_bsm_link', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endeavor', 'la_s3_ref_template_bsm_link')
    op.drop_column('endeavor', 'lr_s3_ref_template_bsm_link')
    op.drop_column('endeavor', 'la_s3_ref_image_link')
    op.drop_column('endeavor', 'lr_s3_ref_image_link')
    # ### end Alembic commands ###
