"""Initial migration

Revision ID: b1dec07e5da9
Revises:
Create Date: 2023-10-12 10:32:04.056977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1dec07e5da9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endeavor',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('lightning_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('liveness_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('s3_link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('external_link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endeavor')
    # ### end Alembic commands ###
