"""remove_pattern_table

Revision ID: cc7d5f98f15d
Revises: f8aac2d044cd
Create Date: 2025-07-18 08:53:02.170331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc7d5f98f15d'
down_revision = 'f8aac2d044cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_pattern')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_pattern',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pattern', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('external_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('aggregate_entity_id', sa.UUID(), server_default=sa.text("'28608d66-a571-44ec-94db-04a00143ff51'::uuid"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='action_pattern_pkey')
    )
    # ### end Alembic commands ###
