"""Add action info field

Revision ID: d7584bb63342
Revises: 7f1ff45e943b
Create Date: 2024-05-03 08:56:33.543867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7584bb63342'
down_revision = '7f1ff45e943b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endeavor', sa.Column('action_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endeavor', 'action_info')
    # ### end Alembic commands ###
