"""null_to_lightning_pattern

Revision ID: dced98c13af1
Revises: 73dd073f4ad8
Create Date: 2026-06-19 11:48:12.979665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dced98c13af1'
down_revision = '73dd073f4ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endeavor', 'lightning_pattern',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)


def downgrade() -> None:
    op.alter_column('endeavor', 'lightning_pattern',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
