"""add_aggregate_entity

Revision ID: f8aac2d044cd
Revises: d7584bb63342
Create Date: 2025-01-30 13:18:27.984883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from settings import DEFAULT_AGGREGATE_ENTITY_TOKEN

# revision identifiers, used by Alembic.
revision = 'f8aac2d044cd'
down_revision = 'd7584bb63342'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_pattern', sa.Column('aggregate_entity_id', postgresql.UUID(as_uuid=True), server_default=DEFAULT_AGGREGATE_ENTITY_TOKEN, nullable=False))
    op.add_column('endeavor', sa.Column('aggregate_entity_id', postgresql.UUID(as_uuid=True), server_default=DEFAULT_AGGREGATE_ENTITY_TOKEN, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('endeavor', 'aggregate_entity_id')
    op.drop_column('action_pattern', 'aggregate_entity_id')
    # ### end Alembic commands ###
